version: '3'
services:  
    postges:
        container_name: postgres_data
        image: postgres:9.6
        environment:
            POSTGRES_DB: 'ffa'
            POSTGRES_USER: 'user_ffa'
            POSTGRES_PASSWORD: '12345'
        ports: 
            - 5432:5432
        volumes: 
            - ../postgre_db:/var/lib/postgresql/